
name: Test the GitHub action in this Repository
on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: Test the GitHub action in this Repository
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test this Action
      id: test-action
      uses: ./
      with:
        owner-repo: replicatedhq/kots
        base: 'v1.81.1'
        head: 'v1.82.0'
        title: '1.82.0'
        description: 'Test description'
        include-pr-links: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the output
      run: echo "${{ env.RELEASE_NOTES }}"