
name: Test
on:
  pull_request:

jobs:
  test_go:
    runs-on: ubuntu-latest
    name: Run go test
    steps:
    - uses: actions/checkout@v3
    - run: go test ./...

  test_action_job:
    runs-on: ubuntu-latest
    name: Test the GitHub action in this Repository
    steps:
    - uses: actions/checkout@v3
    - name: Test this Action
      id: test-action
      uses: ./
      with:
        owner-repo: replicatedhq/kots
        base: 'v1.81.1'
        head: 'v1.82.0'
        title: '1.82.0'
        description: 'Support for Kubernetes: 1.21, 1.22, 1.23, and 1.24'
        include-pr-links: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print the output
      run: echo "${{ steps.test-action.outputs.release-notes }}"